### ISSUE TITLE
Recipe.xml 테이블명, 컬럼명 불일치

### ISSUE THREAD

**Issue by juddammu** [opensource-brewduck/brewduck#2]
--recipes.xml 테이블명 변경--

RECIPE			--> RECIPES
RECIPE_FERMENTABLE	--> RECIPES_FERMENTABLES
RECIPE_HOPS		--> RECIPES_HOPS
RECIPE_YEAST		--> RECIPES_YEASTS
RECIPE_MISC		--> RECIPES_MISCS

--recipes.xml 컬럼 변경--

SEQ                     --> ID
TYPE                    --> TYPE_CODE
BREWER                  --> BREWER_ID
ASST_BREWER             -->ASST_BREWER _ID
PRIMARY_AGE		--> 대응컬럼?
PRIMARY_TEMP            --> 대응컬럼?
SECONDARY_AGE           --> 대응컬럼?     
SECONDARY_TEMP          --> 대응컬럼?    
AGE                     --> 대응컬럼?                                
PRIMING_SUGAR_NAME	--> 대응컬럼?
READ_COUNT		--> 대응컬럼?        
atch_file_id		--> 대응컬럼?     
atch_cover_file_id	--> 대응컬럼?

**Comment by hukoru** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

hukoru@naver.com 님께 보내신 메일 <[brewduck] Recipe.xml 테이블명, 컬럼명 불일치 (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hukoru** [comment]
소스가 최신소스가 아닌것 같습니다. 다시 받아보세요~~
