### ISSUE TITLE
재료데이터 베이스 디테일 뷰 댓글 개수 노출 안됨

### ISSUE THREAD

**Issue by juddammu** [opensource-brewduck/brewduck#4]
재료데이터 베이스 디테일 뷰의
댓글 입력창 위 댓글 개수 텍스트 노출 안됨

**Comment by hukoru** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

hukoru@naver.com 님께 보내신 메일 <[brewduck] 재료데이터 베이스 디테일 뷰 댓글 개수 노출 안됨 (#4)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by juddammu** [comment]
![fix_replycount](https://cloud.githubusercontent.com/assets/5144441/6995955/dfe9e77e-dba4-11e4-99c0-2202b06f9b90.PNG)
댓글 카운트 노출 완료

**Comment by hukoru** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

hukoru@naver.com 님께 보내신 메일 <Re: [brewduck] 재료데이터 베이스 디테일 뷰 댓글 개수 노출 안됨 (#4)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
